language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
matrix:
  include:
    - rust: nightly-2018-03-06
      env:
        - CLIPPY_VERSION=0.0.187
      before_script:
        - cargo install rustfmt-nightly --force
        - cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
      script:
        - cargo fmt -- --write-mode=diff
        - cargo clippy
