[package]
name = "polytype"
version = "4.2.0"
authors = ["Lucas Morales <lucas@lucasem.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/lucasem/polytype-rs"
homepage = "https://github.com/lucasem/polytype-rs"
documentation = "https://docs.rs/polytype"
description = "A Hindley-Milner polymorphic typing system."
keywords = ["typing", "language", "type", "inference", "unification"]
categories = ["science", "data-structures", "algorithms"]

[dependencies]
itertools = "0.7"
nom = "4.0.0-beta3"
